### ISSUE TITLE
Can I use this for mpgs?

### ISSUE THREAD

**Issue by syahnur197** [thephpleague/omnipay-migs#15]
Mastercard rebranded migs to mpgs, can I still use this package for mpgs?

**Comment by syahnur197** [comment]
I also want to use this for laravel, but for some reason I cannot install it, please helo

**Comment by digistorm-developer** [comment]
I know it's been over a year, but I ran into the same issue and ended up making an omnipay wrapper for MPGS. It only supports a purchase (PAY) transaction at the moment.

https://github.com/digistorm/omnipay-mpgs
