### ISSUE TITLE
the use of MD5 algorithms will no longer be accepted by the MasterCard Payment Gateway. 

### ISSUE THREAD

**Issue by aladdinkh** [thephpleague/omnipay-migs#9]
The secure hash feature has changed  from MD5 to SHA256
Is this something you are aware off. this change is worldwide
Can you update the omnipay plug in

the use of MD5 algorithms will no longer be accepted by the MasterCard Payment Gateway. Merchants currently using MD5 algorithms will need to upgrade to SHA256 algorithms to avoid interruption to service 

Can we update the omnipay??

**Comment by lucasnetau** [comment]
Release 2.2.1 of omnipay-migs released on the 22nd September 2015 supports SHA256 by default and MD5 support was removed.
